if has("win32")                     " GUI font
    set guifont=Fira_Mono:h12:cANSI
elseif has("macunix")
    set guifont=Fira\ Mono:h12
else
    set guifont=Fira\ Mono\ 12
endif

set guioptions=c                    " Hide GUI elements
set guicursor+=a:blinkon0           " Disable cursor blink

colorscheme jellybeans              " Set colorscheme
