if has("win32")                     " GUI font
    set guifont=Fira_Mono:h12:cANSI
else
    set guifont=Fira\ Mono\ 12
endif

set guioptions=rb                   " Hide GUI elements
set guicursor+=a:blinkon0           " Disable cursor blink

colorscheme bensday                 " Set colorscheme
